# Generated by Django 5.1 on 2024-08-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(verbose_name='消費期限'),
        ),
    ]
