# Generated by Django 5.1 on 2024-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='品物'),
        ),
        migrations.AlterField(
            model_name='food',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='数量'),
        ),
    ]
